# Static analysis using Polaris on pull requests to master

name: Polaris Scan

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 7 * * 0'

jobs:
  security:
    name: Static analysis
    runs-on: ubuntu-latest

    steps:
    # Checkout to source branch on pull request
    - name: Checkout repository on PR
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
      
    # Checkout
    - name: Checkout
      if: ${{ github.event_name != 'pull_request' }}
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.5' 
        
    # Export secrets, download polaris client and analyze
    - name: Static Analysis with Polaris
      run: |
        export POLARIS_SERVER_URL=${{secrets.POLARIS_SERVER_URL}}
        export POLARIS_ACCESS_TOKEN=${{secrets.POLARIS_ACCESS_TOKEN}}
        wget -q ${{secrets.POLARIS_SERVER_URL}}/api/tools/polaris_cli-linux64.zip
        unzip -j -o polaris_cli-linux64.zip -d /tmp
        /tmp/polaris analyze
        
